# Generated by Django 5.0.7 on 2026-06-26 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('voided', 'Voided')], default='pending_review', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_email_sent', models.BooleanField(default=False)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='residents.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payment_evidence/')),
                ('source', models.CharField(default='student_portal', max_length=60)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='payments.payment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='payment_amount_nonnegative'),
        ),
    ]
